# inherit all settings from .github repo
_extends: .github
repository:
  description: >-
    resolves a promise with your chosen selection from state when the state
    allows your predicate to return true
  homepage: 'https://npm.im/redux-select-when-matched'
