repository:
  description: >-
    resolves a promise with your chosen selection from state when the state
    allows your predicate to return true
  homepage: 'https://npm.im/redux-select-when-matched'
  has_wiki: false
  has_projects: false
  has_downloads: false
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: true
labels:
  - name: bug
    color: ee0701
  - name: duplicate
    color: cccccc
  - name: enhancement
    color: 84b6eb
  - name: help wanted
    color: 128A0C
  - name: invalid
    color: e6e6e6
  - name: question
    color: cc317c
  - name: wontfix
    color: ffffff
  - name: greenkeeper
    color: 00c775
branches:
  - name: master
    protection:
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
      enforce_admins: true
teams:
  - name: front-end
    permission: push
